// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABDG1nnx_DodfyofwG4L9QZwF0NL6olAc',
    appId: '1:919153588919:web:cf6f34348ca1807fee6b32',
    messagingSenderId: '919153588919',
    projectId: 'mobile-chat-app-62df7',
    authDomain: 'mobile-chat-app-62df7.firebaseapp.com',
    storageBucket: 'mobile-chat-app-62df7.appspot.com',
    measurementId: 'G-N6M9GMBYEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsE4bdC3mvW841XGORnPbmwWV3AWJm6FM',
    appId: '1:919153588919:android:2d301a04b71008fbee6b32',
    messagingSenderId: '919153588919',
    projectId: 'mobile-chat-app-62df7',
    storageBucket: 'mobile-chat-app-62df7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4phSevXGv-XPnT-iPFwDnwVm-RvruqjY',
    appId: '1:919153588919:ios:b21dd9adb82f15e3ee6b32',
    messagingSenderId: '919153588919',
    projectId: 'mobile-chat-app-62df7',
    storageBucket: 'mobile-chat-app-62df7.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
